version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: 'nextjs'
    volumes:
      - ./container:/home/web
    tty:
      true
    ports:
      - 3000:3000
